[workspace]
resolver = "2"
members = [
    "web_server",
    "agent_core",
    "agent_tools",
    "agent_api",
    "agent_llm",
    "agent_orchestrator",
    "demo_agent"
    #"py_bridge"
]

[workspace.dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
